apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: hugo-site-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hugo-site
  policy:
    semver:
      range: "*"