---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: aj-blogs-docker-registry
  namespace: flux-system
spec:
  image: bozosapien/hugo-site
  interval: 1m0s
  secretRef:
    name: dockerhub-credentials
